### PR TITLE
header-footer minimal view

### PR DESCRIPTION
**Pull request by rak2112**

### CODE REVIEW

**Comment by jamesbirrellgray** [comment]
@rak2112 Do we have any movement on this?

**Comment by jamesbirrellgray** [comment]
@trevorsaint @scarlz - do you want to approve this?

**Comment by jamesbirrellgray** [comment]
@rak2112 I have now reviewed this. It seems yo have updated the existing components instead of creating new ones as discussed? @scarlz was this the approach discussed?

I think the "minimal" header and footer should be a separate component. Agreed @fabiotisci

**Comment by smythb1981** [comment]
You can view the story which its blocking progress on IDAM.
https://triadmoj.atlassian.net/browse/IDAMJL-1772

This lists all the other stories this PDK update is blocking and also relates to https://triadmoj.atlassian.net/browse/IDAMJL-1773

**Pull request merged**
